# Generated by Django 3.2.6 on 2021-09-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0004_auto_20210903_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
